import type {
  Supplier,
  RFQ,
  Quotation,
  InventoryItem,
  SpendDataPoint,
  CategorySpend,
  Recommendation,
  PriceForecast,
  Notification,
  PurchaseOrder,
} from './types';

function riskLevelFromScore(score: number): 'HIGH' | 'MEDIUM' | 'LOW' {
  if (score >= 70) return 'HIGH';
  if (score >= 40) return 'MEDIUM';
  return 'LOW';
}

export const suppliers: Supplier[] = [
  {
    id: 'SUP-001',
    name: 'Global Materials Ltd.',
    category: 'Raw Materials',
    location: 'Mumbai, India',
    spend: 248000,
    performance: 72,
    deliveryRate: 78,
    qualityScore: 81,
    riskScore: 82,
    riskLevel: 'HIGH',
    status: 'Under Review',
    contactEmail: 'contact@globalmaterials.com',
    contactPhone: '+91 22 4567 8901',
    website: 'www.globalmaterials.com',
    founded: 1998,
    employees: 1200,
    annualRevenue: '$45M',
    onTimeDelivery: 78,
    totalOrders: 342,
    activeContracts: 4,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001', 'ISO 14001'],
    riskBreakdown: { financial: 90, delivery: 82, quality: 71, priceStability: 80 },
    recentTransactions: [
      { id: 'TXN-1042', date: '2026-08-10', amount: 42000, product: 'Steel Coils', status: 'Delivered' },
      { id: 'TXN-1038', date: '2026-07-28', amount: 38500, product: 'Aluminum Sheets', status: 'Delivered' },
      { id: 'TXN-1031', date: '2026-07-15', amount: 51200, product: 'Steel Plates', status: 'Delayed' },
      { id: 'TXN-1025', date: '2026-06-30', amount: 33800, product: 'Copper Rods', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-001', 'RFQ-2026-003'],
    aiAnalysis:
      'Risk increased because delivery delays increased by 27%, quality complaints increased by 12%, and financial stability indicators deteriorated during the previous quarter. Recommend activating backup supplier and reducing order volume by 30%.',
  },
  {
    id: 'SUP-002',
    name: 'Prime Components',
    category: 'Components',
    location: 'Pune, India',
    spend: 186000,
    performance: 84,
    deliveryRate: 88,
    qualityScore: 86,
    riskScore: 55,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'sales@primecomponents.com',
    contactPhone: '+91 20 2345 6789',
    website: 'www.primecomponents.com',
    founded: 2005,
    employees: 850,
    annualRevenue: '$32M',
    onTimeDelivery: 88,
    totalOrders: 278,
    activeContracts: 3,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'IATF 16949'],
    riskBreakdown: { financial: 48, delivery: 62, quality: 55, priceStability: 50 },
    recentTransactions: [
      { id: 'TXN-1045', date: '2026-08-12', amount: 28400, product: 'Precision Gears', status: 'Delivered' },
      { id: 'TXN-1040', date: '2026-07-25', amount: 32100, product: 'Bearings', status: 'Delivered' },
      { id: 'TXN-1033', date: '2026-07-18', amount: 24800, product: 'Shafts', status: 'Delayed' },
    ],
    recentRFQs: ['RFQ-2026-001', 'RFQ-2026-005'],
    aiAnalysis:
      'Delivery delays are trending upward (up 15% over last quarter) but quality remains strong. Medium risk driven primarily by delivery performance. Consider renegotiating lead-time SLAs.',
  },
  {
    id: 'SUP-003',
    name: 'TechSource Industries',
    category: 'Electronics',
    location: 'Bengaluru, India',
    spend: 312000,
    performance: 91,
    deliveryRate: 94,
    qualityScore: 93,
    riskScore: 22,
    riskLevel: 'LOW',
    status: 'Preferred',
    contactEmail: 'info@techsourceind.com',
    contactPhone: '+91 80 3456 7890',
    website: 'www.techsourceind.com',
    founded: 2010,
    employees: 2100,
    annualRevenue: '$78M',
    onTimeDelivery: 94,
    totalOrders: 456,
    activeContracts: 6,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 27001'],
    riskBreakdown: { financial: 18, delivery: 25, quality: 20, priceStability: 28 },
    recentTransactions: [
      { id: 'TXN-1048', date: '2026-08-14', amount: 62000, product: 'Circuit Boards', status: 'Delivered' },
      { id: 'TXN-1043', date: '2026-08-01', amount: 48500, product: 'Sensors', status: 'Delivered' },
      { id: 'TXN-1036', date: '2026-07-20', amount: 55200, product: 'Connectors', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-002', 'RFQ-2026-004'],
    aiAnalysis:
      'Top-performing supplier with consistently high delivery (94%) and quality (93%) scores. Low financial risk and stable pricing. Ideal candidate for increased volume and long-term contract.',
  },
  {
    id: 'SUP-004',
    name: 'Apex Manufacturing',
    category: 'Machined Parts',
    location: 'Chennai, India',
    spend: 164000,
    performance: 88,
    deliveryRate: 90,
    qualityScore: 89,
    riskScore: 35,
    riskLevel: 'LOW',
    status: 'Active',
    contactEmail: 'orders@apexmfg.com',
    contactPhone: '+91 44 5678 9012',
    website: 'www.apexmfg.com',
    founded: 2002,
    employees: 980,
    annualRevenue: '$28M',
    onTimeDelivery: 90,
    totalOrders: 312,
    activeContracts: 4,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'AS9100D'],
    riskBreakdown: { financial: 30, delivery: 38, quality: 32, priceStability: 40 },
    recentTransactions: [
      { id: 'TXN-1046', date: '2026-08-11', amount: 36200, product: 'Machined Brackets', status: 'Delivered' },
      { id: 'TXN-1039', date: '2026-07-27', amount: 41500, product: 'Custom Housings', status: 'Delivered' },
      { id: 'TXN-1032', date: '2026-07-14', amount: 29800, product: 'Valves', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-003', 'RFQ-2026-006'],
    aiAnalysis:
      'Reliable supplier with stable performance across all metrics. Low risk profile. Good candidate for preferred supplier status and expanded product lines.',
  },
  {
    id: 'SUP-005',
    name: 'SteelWorks India',
    category: 'Raw Materials',
    location: 'Kolkata, India',
    spend: 198000,
    performance: 76,
    deliveryRate: 82,
    qualityScore: 79,
    riskScore: 68,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'contact@steelworksindia.com',
    contactPhone: '+91 33 6789 0123',
    website: 'www.steelworksindia.com',
    founded: 1995,
    employees: 1500,
    annualRevenue: '$52M',
    onTimeDelivery: 82,
    totalOrders: 389,
    activeContracts: 5,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001', 'ISO 14001'],
    riskBreakdown: { financial: 65, delivery: 72, quality: 68, priceStability: 75 },
    recentTransactions: [
      { id: 'TXN-1044', date: '2026-08-09', amount: 45800, product: 'Steel Beams', status: 'Delivered' },
      { id: 'TXN-1037', date: '2026-07-22', amount: 52300, product: 'Steel Pipes', status: 'Delayed' },
      { id: 'TXN-1030', date: '2026-07-10', amount: 39100, product: 'Steel Rods', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-001', 'RFQ-2026-007'],
    aiAnalysis:
      'Medium risk driven by price volatility (75) and delivery inconsistency. Steel price exposure is a concern. Recommend locking in prices with a 6-month forward contract.',
  },
  {
    id: 'SUP-006',
    name: 'Nova Electronics',
    category: 'Electronics',
    location: 'Hyderabad, India',
    spend: 274000,
    performance: 89,
    deliveryRate: 91,
    qualityScore: 90,
    riskScore: 28,
    riskLevel: 'LOW',
    status: 'Preferred',
    contactEmail: 'sales@novaelectronics.com',
    contactPhone: '+91 40 7890 1234',
    website: 'www.novaelectronics.com',
    founded: 2008,
    employees: 1800,
    annualRevenue: '$65M',
    onTimeDelivery: 91,
    totalOrders: 401,
    activeContracts: 5,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'ISO 27001', 'RoHS'],
    riskBreakdown: { financial: 22, delivery: 30, quality: 25, priceStability: 35 },
    recentTransactions: [
      { id: 'TXN-1047', date: '2026-08-13', amount: 58400, product: 'Microcontrollers', status: 'Delivered' },
      { id: 'TXN-1041', date: '2026-07-29', amount: 44900, product: 'PCB Assemblies', status: 'Delivered' },
      { id: 'TXN-1035', date: '2026-07-16', amount: 51200, product: 'Power Modules', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-002', 'RFQ-2026-008'],
    aiAnalysis:
      'Strong performer with low risk across all dimensions. Electronics supply chain is stable. Recommend consolidating electronics sourcing with Nova for volume discounts.',
  },
  {
    id: 'SUP-007',
    name: 'Precision Forge Co.',
    category: 'Forged Parts',
    location: 'Coimbatore, India',
    spend: 142000,
    performance: 85,
    deliveryRate: 87,
    qualityScore: 88,
    riskScore: 42,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'info@precisionforge.com',
    contactPhone: '+91 422 890 1234',
    website: 'www.precisionforge.com',
    founded: 2001,
    employees: 720,
    annualRevenue: '$22M',
    onTimeDelivery: 87,
    totalOrders: 256,
    activeContracts: 3,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'IATF 16949'],
    riskBreakdown: { financial: 40, delivery: 45, quality: 38, priceStability: 48 },
    recentTransactions: [
      { id: 'TXN-1049', date: '2026-08-15', amount: 32100, product: 'Forged Flanges', status: 'Delivered' },
      { id: 'TXN-1042', date: '2026-07-24', amount: 28400, product: 'Forged Fittings', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-004', 'RFQ-2026-006'],
    aiAnalysis:
      'Medium risk with moderate delivery variability. Quality is consistently good. Consider a dual-sourcing strategy to hedge against delivery delays.',
  },
  {
    id: 'SUP-008',
    name: 'PolyChem Industries',
    category: 'Chemicals',
    location: 'Vadodara, India',
    spend: 128000,
    performance: 81,
    deliveryRate: 85,
    qualityScore: 83,
    riskScore: 48,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'sales@polychemind.com',
    contactPhone: '+91 265 901 2345',
    website: 'www.polychemind.com',
    founded: 1999,
    employees: 650,
    annualRevenue: '$18M',
    onTimeDelivery: 85,
    totalOrders: 198,
    activeContracts: 2,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001', 'ISO 14001', 'REACH'],
    riskBreakdown: { financial: 45, delivery: 50, quality: 42, priceStability: 55 },
    recentTransactions: [
      { id: 'TXN-1050', date: '2026-08-15', amount: 24800, product: 'Industrial Resins', status: 'Delivered' },
      { id: 'TXN-1043', date: '2026-07-26', amount: 31200, product: 'Polymer Compounds', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-005', 'RFQ-2026-009'],
    aiAnalysis:
      'Medium risk driven by chemical price volatility and moderate delivery performance. Quality is acceptable. Monitor raw material price exposure closely.',
  },
  {
    id: 'SUP-009',
    name: 'AutoFast Systems',
    category: 'Fasteners',
    location: 'Gurugram, India',
    spend: 96000,
    performance: 87,
    deliveryRate: 89,
    qualityScore: 86,
    riskScore: 38,
    riskLevel: 'LOW',
    status: 'Active',
    contactEmail: 'orders@autofast.com',
    contactPhone: '+91 124 012 3456',
    website: 'www.autofast.com',
    founded: 2007,
    employees: 540,
    annualRevenue: '$15M',
    onTimeDelivery: 89,
    totalOrders: 287,
    activeContracts: 3,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'IATF 16949'],
    riskBreakdown: { financial: 32, delivery: 40, quality: 35, priceStability: 42 },
    recentTransactions: [
      { id: 'TXN-1051', date: '2026-08-14', amount: 18200, product: 'High-Tensile Bolts', status: 'Delivered' },
      { id: 'TXN-1044', date: '2026-07-28', amount: 22500, product: 'Specialty Fasteners', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-006', 'RFQ-2026-010'],
    aiAnalysis:
      'Reliable fastener supplier with low risk and consistent performance. Good candidate for blanket PO agreements to reduce transaction costs.',
  },
  {
    id: 'SUP-010',
    name: 'GreenPack Packaging',
    category: 'Packaging',
    location: 'Nashik, India',
    spend: 78000,
    performance: 90,
    deliveryRate: 92,
    qualityScore: 88,
    riskScore: 25,
    riskLevel: 'LOW',
    status: 'Preferred',
    contactEmail: 'info@greenpack.com',
    contactPhone: '+91 253 123 4567',
    website: 'www.greenpack.com',
    founded: 2012,
    employees: 420,
    annualRevenue: '$12M',
    onTimeDelivery: 92,
    totalOrders: 234,
    activeContracts: 2,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'FSC Certified'],
    riskBreakdown: { financial: 20, delivery: 28, quality: 22, priceStability: 30 },
    recentTransactions: [
      { id: 'TXN-1052', date: '2026-08-13', amount: 15800, product: 'Corrugated Boxes', status: 'Delivered' },
      { id: 'TXN-1045', date: '2026-07-30', amount: 19400, product: 'Pallets', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-007', 'RFQ-2026-010'],
    aiAnalysis:
      'Sustainable packaging supplier with excellent delivery and low risk. FSC certified. Recommend for ESG-aligned procurement initiatives.',
  },
  {
    id: 'SUP-011',
    name: 'ThermoCast Foundry',
    category: 'Castings',
    location: 'Rajkot, India',
    spend: 134000,
    performance: 79,
    deliveryRate: 83,
    qualityScore: 80,
    riskScore: 58,
    riskLevel: 'MEDIUM',
    status: 'Under Review',
    contactEmail: 'sales@thermocast.com',
    contactPhone: '+91 281 234 5678',
    website: 'www.thermocast.com',
    founded: 2000,
    employees: 680,
    annualRevenue: '$20M',
    onTimeDelivery: 83,
    totalOrders: 245,
    activeContracts: 3,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001'],
    riskBreakdown: { financial: 55, delivery: 62, quality: 52, priceStability: 60 },
    recentTransactions: [
      { id: 'TXN-1053', date: '2026-08-12', amount: 28100, product: 'Iron Castings', status: 'Delayed' },
      { id: 'TXN-1046', date: '2026-07-25', amount: 31400, product: 'Ductile Iron Parts', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-003', 'RFQ-2026-008'],
    aiAnalysis:
      'Under review due to recent delivery delays and quality complaints. Medium risk. Recommend a 90-day performance improvement plan before renewing contracts.',
  },
  {
    id: 'SUP-012',
    name: 'ElectroDrive Motors',
    category: 'Electronics',
    location: 'Ahmedabad, India',
    spend: 205000,
    performance: 86,
    deliveryRate: 88,
    qualityScore: 87,
    riskScore: 40,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'info@electrodrive.com',
    contactPhone: '+91 79 345 6789',
    website: 'www.electrodrive.com',
    founded: 2006,
    employees: 1100,
    annualRevenue: '$38M',
    onTimeDelivery: 88,
    totalOrders: 312,
    activeContracts: 4,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'CE Marked'],
    riskBreakdown: { financial: 38, delivery: 42, quality: 35, priceStability: 45 },
    recentTransactions: [
      { id: 'TXN-1054', date: '2026-08-14', amount: 42800, product: 'Servo Motors', status: 'Delivered' },
      { id: 'TXN-1047', date: '2026-07-27', amount: 38500, product: 'Stepper Motors', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-002', 'RFQ-2026-009'],
    aiAnalysis:
      'Medium risk with stable performance. Motor supply chain has moderate exposure to rare-earth material prices. Consider hedging strategy.',
  },
  {
    id: 'SUP-013',
    name: 'Hydraulic Solutions',
    category: 'Components',
    location: 'Faridabad, India',
    spend: 112000,
    performance: 83,
    deliveryRate: 85,
    qualityScore: 84,
    riskScore: 45,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'sales@hydraulicsolutions.com',
    contactPhone: '+91 129 456 7890',
    website: 'www.hydraulicsolutions.com',
    founded: 2004,
    employees: 590,
    annualRevenue: '$16M',
    onTimeDelivery: 85,
    totalOrders: 198,
    activeContracts: 3,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001'],
    riskBreakdown: { financial: 42, delivery: 48, quality: 40, priceStability: 50 },
    recentTransactions: [
      { id: 'TXN-1055', date: '2026-08-11', amount: 24600, product: 'Hydraulic Cylinders', status: 'Delivered' },
      { id: 'TXN-1048', date: '2026-07-26', amount: 28900, product: 'Hydraulic Pumps', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-005', 'RFQ-2026-010'],
    aiAnalysis:
      'Medium risk supplier with consistent but not exceptional performance. Quality is reliable. Good secondary source for hydraulic components.',
  },
  {
    id: 'SUP-014',
    name: 'PlastiForm Molding',
    category: 'Plastics',
    location: 'Vapi, India',
    spend: 89000,
    performance: 88,
    deliveryRate: 90,
    qualityScore: 87,
    riskScore: 32,
    riskLevel: 'LOW',
    status: 'Active',
    contactEmail: 'info@plastiform.com',
    contactPhone: '+91 260 567 8901',
    website: 'www.plastiform.com',
    founded: 2009,
    employees: 480,
    annualRevenue: '$14M',
    onTimeDelivery: 90,
    totalOrders: 221,
    activeContracts: 2,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'ISO 14001'],
    riskBreakdown: { financial: 28, delivery: 35, quality: 30, priceStability: 38 },
    recentTransactions: [
      { id: 'TXN-1056', date: '2026-08-13', amount: 19200, product: 'Injection Molded Parts', status: 'Delivered' },
      { id: 'TXN-1049', date: '2026-07-28', amount: 21800, product: 'Plastic Enclosures', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-007', 'RFQ-2026-009'],
    aiAnalysis:
      'Low risk plastic molding supplier with strong delivery performance. Stable pricing. Good candidate for increased volume and long-term agreement.',
  },
  {
    id: 'SUP-015',
    name: 'MetalCraft Fabrication',
    category: 'Fabrication',
    location: 'Ludhiana, India',
    spend: 156000,
    performance: 82,
    deliveryRate: 84,
    qualityScore: 85,
    riskScore: 50,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'orders@metalcraft.com',
    contactPhone: '+91 161 678 9012',
    website: 'www.metalcraft.com',
    founded: 2003,
    employees: 760,
    annualRevenue: '$24M',
    onTimeDelivery: 84,
    totalOrders: 268,
    activeContracts: 3,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001', 'AWS Certified'],
    riskBreakdown: { financial: 48, delivery: 52, quality: 45, priceStability: 55 },
    recentTransactions: [
      { id: 'TXN-1057', date: '2026-08-12', amount: 32400, product: 'Welded Assemblies', status: 'Delivered' },
      { id: 'TXN-1050', date: '2026-07-25', amount: 28100, product: 'Sheet Metal Parts', status: 'Delayed' },
    ],
    recentRFQs: ['RFQ-2026-006', 'RFQ-2026-008'],
    aiAnalysis:
      'Medium risk fabrication supplier with moderate delivery variability. Quality is good. Steel price exposure affects margins. Consider indexing contract to steel benchmark.',
  },
  {
    id: 'SUP-016',
    name: 'CircuitPro Electronics',
    category: 'Electronics',
    location: 'Noida, India',
    spend: 188000,
    performance: 92,
    deliveryRate: 93,
    qualityScore: 94,
    riskScore: 20,
    riskLevel: 'LOW',
    status: 'Preferred',
    contactEmail: 'sales@circuitpro.com',
    contactPhone: '+91 120 789 0123',
    website: 'www.circuitpro.com',
    founded: 2011,
    employees: 1600,
    annualRevenue: '$55M',
    onTimeDelivery: 93,
    totalOrders: 378,
    activeContracts: 5,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'ISO 27001', 'UL Listed'],
    riskBreakdown: { financial: 15, delivery: 22, quality: 18, priceStability: 25 },
    recentTransactions: [
      { id: 'TXN-1058', date: '2026-08-15', amount: 48200, product: 'PCBs', status: 'Delivered' },
      { id: 'TXN-1051', date: '2026-07-30', amount: 52400, product: 'Electronic Assemblies', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-002', 'RFQ-2026-004'],
    aiAnalysis:
      'Top-tier electronics supplier with exceptional quality (94) and delivery (93). Very low risk. Ideal for strategic partnership and volume consolidation.',
  },
  {
    id: 'SUP-017',
    name: 'RubberTech Products',
    category: 'Rubber Parts',
    location: 'Kochi, India',
    spend: 67000,
    performance: 84,
    deliveryRate: 86,
    qualityScore: 83,
    riskScore: 44,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'info@rubbertech.com',
    contactPhone: '+91 484 890 1234',
    website: 'www.rubbertech.com',
    founded: 2008,
    employees: 380,
    annualRevenue: '$9M',
    onTimeDelivery: 86,
    totalOrders: 167,
    activeContracts: 2,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001'],
    riskBreakdown: { financial: 40, delivery: 46, quality: 42, priceStability: 48 },
    recentTransactions: [
      { id: 'TXN-1059', date: '2026-08-10', amount: 14200, product: 'Rubber Gaskets', status: 'Delivered' },
      { id: 'TXN-1052', date: '2026-07-24', amount: 16800, product: 'O-Rings', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-009', 'RFQ-2026-010'],
    aiAnalysis:
      'Medium risk rubber parts supplier. Natural rubber price volatility is the primary risk driver. Quality and delivery are acceptable for non-critical components.',
  },
  {
    id: 'SUP-018',
    name: 'AlloyForge Industries',
    category: 'Forged Parts',
    location: 'Jamshedpur, India',
    spend: 175000,
    performance: 80,
    deliveryRate: 82,
    qualityScore: 83,
    riskScore: 62,
    riskLevel: 'MEDIUM',
    status: 'Active',
    contactEmail: 'sales@alloyforge.com',
    contactPhone: '+91 657 901 2345',
    website: 'www.alloyforge.com',
    founded: 1997,
    employees: 1300,
    annualRevenue: '$42M',
    onTimeDelivery: 82,
    totalOrders: 298,
    activeContracts: 4,
    paymentTerms: 'Net 45',
    certifications: ['ISO 9001', 'IATF 16949'],
    riskBreakdown: { financial: 58, delivery: 68, quality: 55, priceStability: 65 },
    recentTransactions: [
      { id: 'TXN-1060', date: '2026-08-11', amount: 38500, product: 'Alloy Forgings', status: 'Delayed' },
      { id: 'TXN-1053', date: '2026-07-23', amount: 42100, product: 'Crankshafts', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-004', 'RFQ-2026-008'],
    aiAnalysis:
      'Medium-high risk driven by delivery delays (68) and alloy price volatility (65). Quality is moderate. Recommend dual-sourcing critical forged components.',
  },
  {
    id: 'SUP-019',
    name: 'WireTech Cables',
    category: 'Electronics',
    location: 'Indore, India',
    spend: 103000,
    performance: 87,
    deliveryRate: 89,
    qualityScore: 86,
    riskScore: 36,
    riskLevel: 'LOW',
    status: 'Active',
    contactEmail: 'info@wiretech.com',
    contactPhone: '+91 731 012 3456',
    website: 'www.wiretech.com',
    founded: 2010,
    employees: 620,
    annualRevenue: '$17M',
    onTimeDelivery: 89,
    totalOrders: 245,
    activeContracts: 3,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'BIS Certified'],
    riskBreakdown: { financial: 30, delivery: 38, quality: 33, priceStability: 42 },
    recentTransactions: [
      { id: 'TXN-1061', date: '2026-08-14', amount: 22300, product: 'Power Cables', status: 'Delivered' },
      { id: 'TXN-1054', date: '2026-07-27', amount: 25600, product: 'Signal Cables', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-002', 'RFQ-2026-010'],
    aiAnalysis:
      'Low risk cable supplier with consistent delivery and quality. Copper price exposure is moderate. Good secondary source for electronic interconnects.',
  },
  {
    id: 'SUP-020',
    name: 'CleanFlow Valves',
    category: 'Components',
    location: 'Nagpur, India',
    spend: 91000,
    performance: 85,
    deliveryRate: 87,
    qualityScore: 86,
    riskScore: 39,
    riskLevel: 'LOW',
    status: 'Onboarding',
    contactEmail: 'sales@cleanflow.com',
    contactPhone: '+91 712 123 4567',
    website: 'www.cleanflow.com',
    founded: 2015,
    employees: 340,
    annualRevenue: '$8M',
    onTimeDelivery: 87,
    totalOrders: 89,
    activeContracts: 1,
    paymentTerms: 'Net 30',
    certifications: ['ISO 9001', 'API Certified'],
    riskBreakdown: { financial: 35, delivery: 42, quality: 38, priceStability: 40 },
    recentTransactions: [
      { id: 'TXN-1062', date: '2026-08-13', amount: 18400, product: 'Ball Valves', status: 'Delivered' },
      { id: 'TXN-1055', date: '2026-07-29', amount: 21200, product: 'Butterfly Valves', status: 'Delivered' },
    ],
    recentRFQs: ['RFQ-2026-005', 'RFQ-2026-007'],
    aiAnalysis:
      'New onboarding supplier showing promising early performance. Low risk. Recommend a pilot program with 3-4 orders before full qualification.',
  },
];

export const rfqs: RFQ[] = [
  {
    id: 'RFQ-2026-001',
    product: 'Industrial Steel Components',
    description: 'High-grade steel components for heavy machinery assembly including brackets, plates, and structural supports.',
    quantity: 10000,
    unit: 'units',
    deadline: '2026-08-25',
    targetPrice: 95,
    suppliersInvited: 5,
    responses: 4,
    status: 'Open',
    category: 'Raw Materials',
    createdDate: '2026-08-01',
    suppliers: ['SUP-001', 'SUP-002', 'SUP-005', 'SUP-011', 'SUP-018'],
  },
  {
    id: 'RFQ-2026-002',
    product: 'Electronic Control Boards',
    description: 'Custom PCB assemblies with microcontroller integration for industrial automation systems.',
    quantity: 5000,
    unit: 'units',
    deadline: '2026-09-10',
    targetPrice: 145,
    suppliersInvited: 4,
    responses: 4,
    status: 'Open',
    category: 'Electronics',
    createdDate: '2026-08-03',
    suppliers: ['SUP-003', 'SUP-006', 'SUP-012', 'SUP-016'],
  },
  {
    id: 'RFQ-2026-003',
    product: 'Precision Machined Housings',
    description: 'CNC-machined aluminum housings with tight tolerances for sensor enclosures.',
    quantity: 8000,
    unit: 'units',
    deadline: '2026-09-05',
    targetPrice: 62,
    suppliersInvited: 4,
    responses: 3,
    status: 'Open',
    category: 'Machined Parts',
    createdDate: '2026-08-05',
    suppliers: ['SUP-004', 'SUP-001', 'SUP-011', 'SUP-015'],
  },
  {
    id: 'RFQ-2026-004',
    product: 'Forged Flange Assemblies',
    description: 'Carbon steel forged flanges with machined surfaces for pipeline connections.',
    quantity: 3000,
    unit: 'units',
    deadline: '2026-09-15',
    targetPrice: 180,
    suppliersInvited: 3,
    responses: 3,
    status: 'Open',
    category: 'Forged Parts',
    createdDate: '2026-08-07',
    suppliers: ['SUP-007', 'SUP-016', 'SUP-018'],
  },
  {
    id: 'RFQ-2026-005',
    product: 'Industrial Polymer Compounds',
    description: 'High-density polymer compounds for injection molding of structural components.',
    quantity: 15000,
    unit: 'kg',
    deadline: '2026-08-30',
    targetPrice: 12,
    suppliersInvited: 3,
    responses: 2,
    status: 'Open',
    category: 'Chemicals',
    createdDate: '2026-08-08',
    suppliers: ['SUP-008', 'SUP-013', 'SUP-020'],
  },
  {
    id: 'RFQ-2026-006',
    product: 'High-Tensile Fastener Kit',
    description: 'Grade 10.9 high-tensile bolt and nut kits with washers for structural assembly.',
    quantity: 50000,
    unit: 'sets',
    deadline: '2026-09-20',
    targetPrice: 4.5,
    suppliersInvited: 4,
    responses: 3,
    status: 'Open',
    category: 'Fasteners',
    createdDate: '2026-08-10',
    suppliers: ['SUP-009', 'SUP-004', 'SUP-015', 'SUP-007'],
  },
  {
    id: 'RFQ-2026-007',
    product: 'Sustainable Packaging Solution',
    description: 'FSC-certified corrugated packaging with custom printing and protective inserts.',
    quantity: 20000,
    unit: 'units',
    deadline: '2026-09-01',
    targetPrice: 3.2,
    suppliersInvited: 3,
    responses: 3,
    status: 'Open',
    category: 'Packaging',
    createdDate: '2026-08-12',
    suppliers: ['SUP-010', 'SUP-014', 'SUP-020'],
  },
  {
    id: 'RFQ-2026-008',
    product: 'Ductile Iron Castings',
    description: 'Ductile iron cast components with machining for agricultural equipment.',
    quantity: 6000,
    unit: 'units',
    deadline: '2026-09-25',
    targetPrice: 85,
    suppliersInvited: 3,
    responses: 2,
    status: 'Open',
    category: 'Castings',
    createdDate: '2026-08-14',
    suppliers: ['SUP-011', 'SUP-018', 'SUP-015'],
  },
  {
    id: 'RFQ-2026-009',
    product: 'Servo Motor Assemblies',
    description: 'Integrated servo motor assemblies with encoders for robotics applications.',
    quantity: 2000,
    unit: 'units',
    deadline: '2026-10-05',
    targetPrice: 320,
    suppliersInvited: 4,
    responses: 3,
    status: 'Open',
    category: 'Electronics',
    createdDate: '2026-08-15',
    suppliers: ['SUP-012', 'SUP-006', 'SUP-008', 'SUP-017'],
  },
  {
    id: 'RFQ-2026-010',
    product: 'Hydraulic Valve Manifolds',
    description: 'Multi-port hydraulic valve manifolds with precision machining and pressure testing.',
    quantity: 1500,
    unit: 'units',
    deadline: '2026-09-30',
    targetPrice: 240,
    suppliersInvited: 4,
    responses: 3,
    status: 'Open',
    category: 'Components',
    createdDate: '2026-08-15',
    suppliers: ['SUP-013', 'SUP-020', 'SUP-009', 'SUP-019'],
  },
  {
    id: 'RFQ-2026-011',
    product: 'Copper Bus Bars',
    description: 'Tinned copper bus bars for electrical distribution panels.',
    quantity: 12000,
    unit: 'units',
    deadline: '2026-09-12',
    targetPrice: 18,
    suppliersInvited: 3,
    responses: 3,
    status: 'Closed',
    category: 'Raw Materials',
    createdDate: '2026-07-15',
    suppliers: ['SUP-001', 'SUP-005', 'SUP-019'],
  },
  {
    id: 'RFQ-2026-012',
    product: 'Plastic Injection Molds',
    description: 'Precision injection molds for consumer electronics enclosures.',
    quantity: 50,
    unit: 'molds',
    deadline: '2026-09-18',
    targetPrice: 4500,
    suppliersInvited: 3,
    responses: 3,
    status: 'Closed',
    category: 'Plastics',
    createdDate: '2026-07-20',
    suppliers: ['SUP-014', 'SUP-008', 'SUP-010'],
  },
  {
    id: 'RFQ-2026-013',
    product: 'Aluminum Extrusion Profiles',
    description: 'Standard and custom aluminum extrusion profiles for structural framing.',
    quantity: 8000,
    unit: 'meters',
    deadline: '2026-09-08',
    targetPrice: 22,
    suppliersInvited: 4,
    responses: 4,
    status: 'Closed',
    category: 'Raw Materials',
    createdDate: '2026-07-10',
    suppliers: ['SUP-001', 'SUP-004', 'SUP-005', 'SUP-015'],
  },
  {
    id: 'RFQ-2026-014',
    product: 'Industrial Rubber Seals',
    description: 'Custom EPDM rubber seals and gaskets for outdoor equipment.',
    quantity: 25000,
    unit: 'units',
    deadline: '2026-09-22',
    targetPrice: 1.8,
    suppliersInvited: 3,
    responses: 2,
    status: 'Closed',
    category: 'Rubber Parts',
    createdDate: '2026-07-25',
    suppliers: ['SUP-017', 'SUP-014', 'SUP-008'],
  },
  {
    id: 'RFQ-2026-015',
    product: 'Welded Steel Subassemblies',
    description: 'Pre-welded steel subassemblies with surface treatment for structural use.',
    quantity: 4000,
    unit: 'units',
    deadline: '2026-09-28',
    targetPrice: 125,
    suppliersInvited: 3,
    responses: 3,
    status: 'Closed',
    category: 'Fabrication',
    createdDate: '2026-07-18',
    suppliers: ['SUP-015', 'SUP-005', 'SUP-011'],
  },
];

export const quotations: Quotation[] = [
  // RFQ-2026-001 - Industrial Steel Components
  { id: 'Q-001-A', rfqId: 'RFQ-2026-001', supplierId: 'SUP-001', supplierName: 'Global Materials Ltd.', price: 98, deliveryDays: 14, qualityScore: 81, paymentTerms: 'Net 45', risk: 'HIGH', historicalPerformance: 72, overallScore: 68 },
  { id: 'Q-001-B', rfqId: 'RFQ-2026-001', supplierId: 'SUP-002', supplierName: 'Prime Components', price: 92, deliveryDays: 14, qualityScore: 86, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 84, overallScore: 84 },
  { id: 'Q-001-C', rfqId: 'RFQ-2026-001', supplierId: 'SUP-005', supplierName: 'SteelWorks India', price: 101, deliveryDays: 5, qualityScore: 97, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 91, overallScore: 95 },
  { id: 'Q-001-D', rfqId: 'RFQ-2026-001', supplierId: 'SUP-011', supplierName: 'ThermoCast Foundry', price: 89, deliveryDays: 21, qualityScore: 80, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 79, overallScore: 76 },

  // RFQ-2026-002 - Electronic Control Boards
  { id: 'Q-002-A', rfqId: 'RFQ-2026-002', supplierId: 'SUP-003', supplierName: 'TechSource Industries', price: 152, deliveryDays: 10, qualityScore: 93, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 91, overallScore: 93 },
  { id: 'Q-002-B', rfqId: 'RFQ-2026-002', supplierId: 'SUP-006', supplierName: 'Nova Electronics', price: 148, deliveryDays: 12, qualityScore: 90, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 89, overallScore: 90 },
  { id: 'Q-002-C', rfqId: 'RFQ-2026-002', supplierId: 'SUP-012', supplierName: 'ElectroDrive Motors', price: 142, deliveryDays: 18, qualityScore: 87, paymentTerms: 'Net 30', risk: 'MEDIUM', historicalPerformance: 86, overallScore: 83 },
  { id: 'Q-002-D', rfqId: 'RFQ-2026-002', supplierId: 'SUP-016', supplierName: 'CircuitPro Electronics', price: 155, deliveryDays: 7, qualityScore: 94, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 92, overallScore: 96 },

  // RFQ-2026-003 - Precision Machined Housings
  { id: 'Q-003-A', rfqId: 'RFQ-2026-003', supplierId: 'SUP-004', supplierName: 'Apex Manufacturing', price: 64, deliveryDays: 8, qualityScore: 89, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 88, overallScore: 90 },
  { id: 'Q-003-B', rfqId: 'RFQ-2026-003', supplierId: 'SUP-001', supplierName: 'Global Materials Ltd.', price: 58, deliveryDays: 18, qualityScore: 81, paymentTerms: 'Net 45', risk: 'HIGH', historicalPerformance: 72, overallScore: 70 },
  { id: 'Q-003-C', rfqId: 'RFQ-2026-003', supplierId: 'SUP-011', supplierName: 'ThermoCast Foundry', price: 61, deliveryDays: 12, qualityScore: 80, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 79, overallScore: 78 },

  // RFQ-2026-004 - Forged Flange Assemblies
  { id: 'Q-004-A', rfqId: 'RFQ-2026-004', supplierId: 'SUP-007', supplierName: 'Precision Forge Co.', price: 185, deliveryDays: 14, qualityScore: 88, paymentTerms: 'Net 30', risk: 'MEDIUM', historicalPerformance: 85, overallScore: 84 },
  { id: 'Q-004-B', rfqId: 'RFQ-2026-004', supplierId: 'SUP-016', supplierName: 'CircuitPro Electronics', price: 192, deliveryDays: 10, qualityScore: 94, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 92, overallScore: 93 },
  { id: 'Q-004-C', rfqId: 'RFQ-2026-004', supplierId: 'SUP-018', supplierName: 'AlloyForge Industries', price: 178, deliveryDays: 20, qualityScore: 83, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 80, overallScore: 76 },

  // RFQ-2026-005 - Industrial Polymer Compounds
  { id: 'Q-005-A', rfqId: 'RFQ-2026-005', supplierId: 'SUP-008', supplierName: 'PolyChem Industries', price: 13, deliveryDays: 12, qualityScore: 83, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 81, overallScore: 80 },
  { id: 'Q-005-B', rfqId: 'RFQ-2026-005', supplierId: 'SUP-013', supplierName: 'Hydraulic Solutions', price: 12.5, deliveryDays: 15, qualityScore: 84, paymentTerms: 'Net 30', risk: 'MEDIUM', historicalPerformance: 83, overallScore: 82 },

  // RFQ-2026-006 - High-Tensile Fastener Kit
  { id: 'Q-006-A', rfqId: 'RFQ-2026-006', supplierId: 'SUP-009', supplierName: 'AutoFast Systems', price: 4.8, deliveryDays: 7, qualityScore: 86, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 87, overallScore: 90 },
  { id: 'Q-006-B', rfqId: 'RFQ-2026-006', supplierId: 'SUP-004', supplierName: 'Apex Manufacturing', price: 5.1, deliveryDays: 10, qualityScore: 89, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 88, overallScore: 88 },
  { id: 'Q-006-C', rfqId: 'RFQ-2026-006', supplierId: 'SUP-015', supplierName: 'MetalCraft Fabrication', price: 4.5, deliveryDays: 14, qualityScore: 85, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 82, overallScore: 80 },

  // RFQ-2026-007 - Sustainable Packaging Solution
  { id: 'Q-007-A', rfqId: 'RFQ-2026-007', supplierId: 'SUP-010', supplierName: 'GreenPack Packaging', price: 3.4, deliveryDays: 5, qualityScore: 88, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 90, overallScore: 93 },
  { id: 'Q-007-B', rfqId: 'RFQ-2026-007', supplierId: 'SUP-014', supplierName: 'PlastiForm Molding', price: 3.1, deliveryDays: 10, qualityScore: 87, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 88, overallScore: 89 },
  { id: 'Q-007-C', rfqId: 'RFQ-2026-007', supplierId: 'SUP-020', supplierName: 'CleanFlow Valves', price: 3.5, deliveryDays: 8, qualityScore: 86, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 85, overallScore: 86 },

  // RFQ-2026-008 - Ductile Iron Castings
  { id: 'Q-008-A', rfqId: 'RFQ-2026-008', supplierId: 'SUP-011', supplierName: 'ThermoCast Foundry', price: 88, deliveryDays: 18, qualityScore: 80, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 79, overallScore: 75 },
  { id: 'Q-008-B', rfqId: 'RFQ-2026-008', supplierId: 'SUP-018', supplierName: 'AlloyForge Industries', price: 82, deliveryDays: 22, qualityScore: 83, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 80, overallScore: 74 },

  // RFQ-2026-009 - Servo Motor Assemblies
  { id: 'Q-009-A', rfqId: 'RFQ-2026-009', supplierId: 'SUP-012', supplierName: 'ElectroDrive Motors', price: 328, deliveryDays: 14, qualityScore: 87, paymentTerms: 'Net 30', risk: 'MEDIUM', historicalPerformance: 86, overallScore: 85 },
  { id: 'Q-009-B', rfqId: 'RFQ-2026-009', supplierId: 'SUP-006', supplierName: 'Nova Electronics', price: 335, deliveryDays: 10, qualityScore: 90, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 89, overallScore: 92 },
  { id: 'Q-009-C', rfqId: 'RFQ-2026-009', supplierId: 'SUP-008', supplierName: 'PolyChem Industries', price: 318, deliveryDays: 20, qualityScore: 83, paymentTerms: 'Net 45', risk: 'MEDIUM', historicalPerformance: 81, overallScore: 78 },

  // RFQ-2026-010 - Hydraulic Valve Manifolds
  { id: 'Q-010-A', rfqId: 'RFQ-2026-010', supplierId: 'SUP-013', supplierName: 'Hydraulic Solutions', price: 245, deliveryDays: 12, qualityScore: 84, paymentTerms: 'Net 30', risk: 'MEDIUM', historicalPerformance: 83, overallScore: 82 },
  { id: 'Q-010-B', rfqId: 'RFQ-2026-010', supplierId: 'SUP-020', supplierName: 'CleanFlow Valves', price: 252, deliveryDays: 8, qualityScore: 86, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 85, overallScore: 88 },
  { id: 'Q-010-C', rfqId: 'RFQ-2026-010', supplierId: 'SUP-009', supplierName: 'AutoFast Systems', price: 248, deliveryDays: 10, qualityScore: 86, paymentTerms: 'Net 30', risk: 'LOW', historicalPerformance: 87, overallScore: 87 },
];

export const inventory: InventoryItem[] = [
  { id: 'INV-001', product: 'Steel Components', sku: 'STL-COMP-001', currentStock: 1200, dailyDemand: 100, reorderPoint: 1800, leadTime: 15, unit: 'units', unitCost: 72, status: 'Critical', category: 'Raw Materials', supplier: 'Global Materials Ltd.' },
  { id: 'INV-002', product: 'Electronic Control Boards', sku: 'ELC-PCB-002', currentStock: 3400, dailyDemand: 120, reorderPoint: 2400, leadTime: 10, unit: 'units', unitCost: 145, status: 'Healthy', category: 'Electronics', supplier: 'TechSource Industries' },
  { id: 'INV-003', product: 'Precision Housings', sku: 'MCH-HSG-003', currentStock: 2100, dailyDemand: 85, reorderPoint: 1700, leadTime: 8, unit: 'units', unitCost: 62, status: 'Healthy', category: 'Machined Parts', supplier: 'Apex Manufacturing' },
  { id: 'INV-004', product: 'Forged Flanges', sku: 'FRG-FLG-004', currentStock: 450, dailyDemand: 45, reorderPoint: 900, leadTime: 14, unit: 'units', unitCost: 180, status: 'Critical', category: 'Forged Parts', supplier: 'Precision Forge Co.' },
  { id: 'INV-005', product: 'Polymer Compounds', sku: 'CHM-POL-005', currentStock: 8500, dailyDemand: 200, reorderPoint: 6000, leadTime: 12, unit: 'kg', unitCost: 12, status: 'Healthy', category: 'Chemicals', supplier: 'PolyChem Industries' },
  { id: 'INV-006', product: 'High-Tensile Bolts', sku: 'FST-BLT-006', currentStock: 32000, dailyDemand: 800, reorderPoint: 16000, leadTime: 7, unit: 'sets', unitCost: 4.5, status: 'Healthy', category: 'Fasteners', supplier: 'AutoFast Systems' },
  { id: 'INV-007', product: 'Corrugated Boxes', sku: 'PKG-BOX-007', currentStock: 5200, dailyDemand: 350, reorderPoint: 7000, leadTime: 5, unit: 'units', unitCost: 3.2, status: 'Low Stock', category: 'Packaging', supplier: 'GreenPack Packaging' },
  { id: 'INV-008', product: 'Ductile Iron Castings', sku: 'CST-IRC-008', currentStock: 1800, dailyDemand: 60, reorderPoint: 1500, leadTime: 18, unit: 'units', unitCost: 85, status: 'Healthy', category: 'Castings', supplier: 'ThermoCast Foundry' },
  { id: 'INV-009', product: 'Servo Motors', sku: 'ELC-SRV-009', currentStock: 280, dailyDemand: 25, reorderPoint: 500, leadTime: 14, unit: 'units', unitCost: 320, status: 'Critical', category: 'Electronics', supplier: 'ElectroDrive Motors' },
  { id: 'INV-010', product: 'Hydraulic Cylinders', sku: 'CMP-HYC-010', currentStock: 640, dailyDemand: 30, reorderPoint: 450, leadTime: 12, unit: 'units', unitCost: 240, status: 'Healthy', category: 'Components', supplier: 'Hydraulic Solutions' },
  { id: 'INV-011', product: 'Injection Molded Parts', sku: 'PLS-MLD-011', currentStock: 9200, dailyDemand: 150, reorderPoint: 4500, leadTime: 10, unit: 'units', unitCost: 8, status: 'Overstocked', category: 'Plastics', supplier: 'PlastiForm Molding' },
  { id: 'INV-012', product: 'Welded Assemblies', sku: 'FAB-WLD-012', currentStock: 1100, dailyDemand: 55, reorderPoint: 1100, leadTime: 12, unit: 'units', unitCost: 125, status: 'Low Stock', category: 'Fabrication', supplier: 'MetalCraft Fabrication' },
  { id: 'INV-013', product: 'Microcontrollers', sku: 'ELC-MCU-013', currentStock: 4200, dailyDemand: 180, reorderPoint: 3600, leadTime: 10, unit: 'units', unitCost: 45, status: 'Healthy', category: 'Electronics', supplier: 'Nova Electronics' },
  { id: 'INV-014', product: 'Rubber Gaskets', sku: 'RBR-GSK-014', currentStock: 18000, dailyDemand: 600, reorderPoint: 12000, leadTime: 8, unit: 'units', unitCost: 1.8, status: 'Healthy', category: 'Rubber Parts', supplier: 'RubberTech Products' },
  { id: 'INV-015', product: 'Alloy Forgings', sku: 'FRG-ALY-015', currentStock: 320, dailyDemand: 40, reorderPoint: 800, leadTime: 20, unit: 'units', unitCost: 165, status: 'Critical', category: 'Forged Parts', supplier: 'AlloyForge Industries' },
  { id: 'INV-016', product: 'Power Cables', sku: 'ELC-CBL-016', currentStock: 5400, dailyDemand: 120, reorderPoint: 3600, leadTime: 10, unit: 'meters', unitCost: 22, status: 'Healthy', category: 'Electronics', supplier: 'WireTech Cables' },
  { id: 'INV-017', product: 'Ball Valves', sku: 'CMP-BLV-017', currentStock: 2100, dailyDemand: 70, reorderPoint: 1400, leadTime: 8, unit: 'units', unitCost: 85, status: 'Healthy', category: 'Components', supplier: 'CleanFlow Valves' },
  { id: 'INV-018', product: 'Copper Bus Bars', sku: 'RAW-CBR-018', currentStock: 800, dailyDemand: 50, reorderPoint: 1000, leadTime: 12, unit: 'units', unitCost: 18, status: 'Low Stock', category: 'Raw Materials', supplier: 'Global Materials Ltd.' },
  { id: 'INV-019', product: 'Aluminum Extrusions', sku: 'RAW-ALX-019', currentStock: 4200, dailyDemand: 100, reorderPoint: 3000, leadTime: 10, unit: 'meters', unitCost: 22, status: 'Healthy', category: 'Raw Materials', supplier: 'Apex Manufacturing' },
  { id: 'INV-020', product: 'Plastic Enclosures', sku: 'PLS-ENC-020', currentStock: 12500, dailyDemand: 200, reorderPoint: 6000, leadTime: 10, unit: 'units', unitCost: 6, status: 'Overstocked', category: 'Plastics', supplier: 'PlastiForm Molding' },
  { id: 'INV-021', product: 'Sensors', sku: 'ELC-SNS-021', currentStock: 1850, dailyDemand: 90, reorderPoint: 1800, leadTime: 10, unit: 'units', unitCost: 35, status: 'Low Stock', category: 'Electronics', supplier: 'TechSource Industries' },
  { id: 'INV-022', product: 'Bearings', sku: 'CMP-BRG-022', currentStock: 6800, dailyDemand: 250, reorderPoint: 5000, leadTime: 7, unit: 'units', unitCost: 12, status: 'Healthy', category: 'Components', supplier: 'Prime Components' },
  { id: 'INV-023', product: 'Steel Pipes', sku: 'RAW-STP-023', currentStock: 2400, dailyDemand: 80, reorderPoint: 2400, leadTime: 15, unit: 'meters', unitCost: 45, status: 'Low Stock', category: 'Raw Materials', supplier: 'SteelWorks India' },
  { id: 'INV-024', product: 'O-Rings', sku: 'RBR-ORG-024', currentStock: 45000, dailyDemand: 1000, reorderPoint: 20000, leadTime: 8, unit: 'units', unitCost: 0.5, status: 'Healthy', category: 'Rubber Parts', supplier: 'RubberTech Products' },
  { id: 'INV-025', product: 'Connectors', sku: 'ELC-CON-025', currentStock: 9800, dailyDemand: 350, reorderPoint: 7000, leadTime: 10, unit: 'units', unitCost: 8, status: 'Healthy', category: 'Electronics', supplier: 'TechSource Industries' },
  { id: 'INV-026', product: 'Shafts', sku: 'CMP-SFT-026', currentStock: 1400, dailyDemand: 60, reorderPoint: 1200, leadTime: 10, unit: 'units', unitCost: 28, status: 'Healthy', category: 'Components', supplier: 'Prime Components' },
  { id: 'INV-027', product: 'Pallets', sku: 'PKG-PLT-027', currentStock: 320, dailyDemand: 40, reorderPoint: 600, leadTime: 5, unit: 'units', unitCost: 15, status: 'Critical', category: 'Packaging', supplier: 'GreenPack Packaging' },
  { id: 'INV-028', product: 'Power Modules', sku: 'ELC-PWR-028', currentStock: 2600, dailyDemand: 110, reorderPoint: 2200, leadTime: 12, unit: 'units', unitCost: 65, status: 'Healthy', category: 'Electronics', supplier: 'Nova Electronics' },
  { id: 'INV-029', product: 'Custom Housings', sku: 'MCH-CHS-029', currentStock: 3800, dailyDemand: 95, reorderPoint: 1900, leadTime: 8, unit: 'units', unitCost: 55, status: 'Overstocked', category: 'Machined Parts', supplier: 'Apex Manufacturing' },
  { id: 'INV-030', product: 'Stepper Motors', sku: 'ELC-STM-030', currentStock: 420, dailyDemand: 35, reorderPoint: 700, leadTime: 14, unit: 'units', unitCost: 85, status: 'Critical', category: 'Electronics', supplier: 'ElectroDrive Motors' },
];

export const monthlySpend: SpendDataPoint[] = [
  { month: 'Sep', spend: 890000, savings: 42000, budget: 950000 },
  { month: 'Oct', spend: 945000, savings: 51000, budget: 980000 },
  { month: 'Nov', spend: 1020000, savings: 58000, budget: 1050000 },
  { month: 'Dec', spend: 1180000, savings: 64000, budget: 1200000 },
  { month: 'Jan', spend: 980000, savings: 49000, budget: 1020000 },
  { month: 'Feb', spend: 1050000, savings: 55000, budget: 1080000 },
  { month: 'Mar', spend: 1120000, savings: 62000, budget: 1150000 },
  { month: 'Apr', spend: 1090000, savings: 58000, budget: 1120000 },
  { month: 'May', spend: 1150000, savings: 67000, budget: 1180000 },
  { month: 'Jun', spend: 1210000, savings: 71000, budget: 1240000 },
  { month: 'Jul', spend: 1140000, savings: 65000, budget: 1180000 },
  { month: 'Aug', spend: 1240000, savings: 78000, budget: 1280000 },
];

export const categorySpend: CategorySpend[] = [
  { category: 'Electronics', spend: 949000, color: 'hsl(213, 94%, 58%)' },
  { category: 'Raw Materials', spend: 446000, color: 'hsl(142, 71%, 45%)' },
  { category: 'Components', spend: 389000, color: 'hsl(38, 92%, 50%)' },
  { category: 'Forged Parts', spend: 317000, color: 'hsl(280, 65%, 60%)' },
  { category: 'Fabrication', spend: 156000, color: 'hsl(340, 75%, 55%)' },
  { category: 'Machined Parts', spend: 164000, color: 'hsl(190, 80%, 50%)' },
  { category: 'Castings', spend: 134000, color: 'hsl(25, 85%, 55%)' },
  { category: 'Other', spend: 89200, color: 'hsl(210, 30%, 50%)' },
];

export const recommendations: Recommendation[] = [
  {
    id: 'REC-001',
    title: 'Supplier Consolidation Opportunity',
    description: 'Consolidating 3 suppliers in the Raw Materials category could reduce costs by approximately 7% through volume discounts and reduced overhead.',
    category: 'COST SAVING',
    priority: 'HIGH',
    impact: '$84,000 annually',
    impactValue: 84000,
    confidence: 91,
    action: 'Review consolidation plan',
    relatedSupplier: 'Global Materials Ltd.',
  },
  {
    id: 'REC-002',
    title: 'Price Increase Predicted',
    description: 'Steel prices may increase over the next 30 days based on market trend analysis and supplier signals. Consider forward-buying 60% of planned quantity.',
    category: 'PRICE',
    priority: 'MEDIUM',
    impact: '$42,000 potential savings',
    impactValue: 42000,
    confidence: 87,
    action: 'Create purchase plan',
    relatedSupplier: 'SteelWorks India',
  },
  {
    id: 'REC-003',
    title: 'High-Risk Supplier Dependency',
    description: 'Global Materials Ltd. accounts for 20% of raw materials spend but has a risk score of 82/100. Recommend activating backup supplier.',
    category: 'RISK',
    priority: 'HIGH',
    impact: 'Risk mitigation',
    impactValue: 0,
    confidence: 94,
    action: 'Run risk analysis',
    relatedSupplier: 'Global Materials Ltd.',
  },
  {
    id: 'REC-004',
    title: 'Inventory Reorder Alert',
    description: 'Steel Components will reach critical level in approximately 8 days. Immediate reorder recommended to avoid stockout.',
    category: 'INVENTORY',
    priority: 'HIGH',
    impact: 'Prevent stockout',
    impactValue: 0,
    confidence: 96,
    action: 'Generate reorder',
  },
  {
    id: 'REC-005',
    title: 'Contract Renewal Opportunity',
    description: 'TechSource Industries contract expires in 45 days. Current performance is excellent (91%). Recommend 2-year renewal with volume discount.',
    category: 'CONTRACT',
    priority: 'MEDIUM',
    impact: '$28,000 savings',
    impactValue: 28000,
    confidence: 89,
    action: 'Review contract',
    relatedSupplier: 'TechSource Industries',
  },
  {
    id: 'REC-006',
    title: 'Maverick Spending Detected',
    description: '12% of last month\'s spend was outside approved supplier list. Enforcing preferred suppliers could save approximately $18K annually.',
    category: 'COST SAVING',
    priority: 'MEDIUM',
    impact: '$18,000 annually',
    impactValue: 18000,
    confidence: 85,
    action: 'Review spend policy',
  },
  {
    id: 'REC-007',
    title: 'Backup Supplier Recommended',
    description: 'Forged Flanges (INV-004) are at critical stock with single-source supplier. Recommend qualifying AlloyForge as secondary source.',
    category: 'SUPPLIER',
    priority: 'MEDIUM',
    impact: 'Supply continuity',
    impactValue: 0,
    confidence: 88,
    action: 'Qualify supplier',
    relatedSupplier: 'AlloyForge Industries',
  },
  {
    id: 'REC-008',
    title: 'Payment Terms Optimization',
    description: 'Switching 4 suppliers from Net 45 to Net 30 could improve cash flow by approximately $120K with early-payment discounts.',
    category: 'COST SAVING',
    priority: 'LOW',
    impact: '$15,000 annually',
    impactValue: 15000,
    confidence: 82,
    action: 'Negotiate terms',
  },
];

export const priceForecasts: PriceForecast[] = [
  {
    material: 'Steel',
    currentPrice: 72,
    unit: '/kg',
    forecast30Day: 78,
    expectedChange: 8.3,
    confidence: 87,
    history: [
      { month: 'Sep', price: 65 }, { month: 'Oct', price: 63 }, { month: 'Nov', price: 66 },
      { month: 'Dec', price: 68 }, { month: 'Jan', price: 67 }, { month: 'Feb', price: 69 },
      { month: 'Mar', price: 70 }, { month: 'Apr', price: 68 }, { month: 'May', price: 71 },
      { month: 'Jun', price: 73 }, { month: 'Jul', price: 72 }, { month: 'Aug', price: 72 },
      { month: 'Sep*', price: 78, predicted: true, upper: 81, lower: 75 },
    ],
    recommendation:
      'Steel prices are predicted to increase over the next 30 days. Consider purchasing 60% of the planned quantity now and the remaining 40% later.',
  },
  {
    material: 'Copper',
    currentPrice: 580,
    unit: '/kg',
    forecast30Day: 562,
    expectedChange: -3.1,
    confidence: 79,
    history: [
      { month: 'Sep', price: 610 }, { month: 'Oct', price: 595 }, { month: 'Nov', price: 605 },
      { month: 'Dec', price: 590 }, { month: 'Jan', price: 585 }, { month: 'Feb', price: 588 },
      { month: 'Mar', price: 592 }, { month: 'Apr', price: 578 }, { month: 'May', price: 583 },
      { month: 'Jun', price: 575 }, { month: 'Jul', price: 580 }, { month: 'Aug', price: 580 },
      { month: 'Sep*', price: 562, predicted: true, upper: 575, lower: 549 },
    ],
    recommendation:
      'Copper prices are predicted to decrease slightly. Consider delaying non-urgent purchases to capture lower prices in 2-3 weeks.',
  },
  {
    material: 'Aluminum',
    currentPrice: 195,
    unit: '/kg',
    forecast30Day: 201,
    expectedChange: 3.1,
    confidence: 84,
    history: [
      { month: 'Sep', price: 185 }, { month: 'Oct', price: 188 }, { month: 'Nov', price: 190 },
      { month: 'Dec', price: 192 }, { month: 'Jan', price: 189 }, { month: 'Feb', price: 191 },
      { month: 'Mar', price: 193 }, { month: 'Apr', price: 194 }, { month: 'May', price: 192 },
      { month: 'Jun', price: 196 }, { month: 'Jul', price: 194 }, { month: 'Aug', price: 195 },
      { month: 'Sep*', price: 201, predicted: true, upper: 206, lower: 196 },
    ],
    recommendation:
      'Aluminum prices are expected to rise moderately. Lock in current prices for the next quarter through forward contracts.',
  },
  {
    material: 'Electronic Components',
    currentPrice: 45,
    unit: '/unit',
    forecast30Day: 47,
    expectedChange: 4.4,
    confidence: 81,
    history: [
      { month: 'Sep', price: 42 }, { month: 'Oct', price: 43 }, { month: 'Nov', price: 42 },
      { month: 'Dec', price: 44 }, { month: 'Jan', price: 43 }, { month: 'Feb', price: 44 },
      { month: 'Mar', price: 45 }, { month: 'Apr', price: 44 }, { month: 'May', price: 45 },
      { month: 'Jun', price: 46 }, { month: 'Jul', price: 45 }, { month: 'Aug', price: 45 },
      { month: 'Sep*', price: 47, predicted: true, upper: 49, lower: 45 },
    ],
    recommendation:
      'Electronic component prices are rising due to chip shortage signals. Recommend increasing safety stock for critical SKUs.',
  },
  {
    material: 'Plastic',
    currentPrice: 12,
    unit: '/kg',
    forecast30Day: 11.5,
    expectedChange: -4.2,
    confidence: 76,
    history: [
      { month: 'Sep', price: 13 }, { month: 'Oct', price: 12.5 }, { month: 'Nov', price: 13 },
      { month: 'Dec', price: 12.8 }, { month: 'Jan', price: 12.2 }, { month: 'Feb', price: 12.5 },
      { month: 'Mar', price: 12.3 }, { month: 'Apr', price: 12 }, { month: 'May', price: 12.2 },
      { month: 'Jun', price: 11.8 }, { month: 'Jul', price: 12 }, { month: 'Aug', price: 12 },
      { month: 'Sep*', price: 11.5, predicted: true, upper: 12, lower: 11 },
    ],
    recommendation:
      'Plastic prices are trending downward. No urgent action needed. Schedule next purchase for 2-3 weeks to capture lower prices.',
  },
];

export const notifications: Notification[] = [
  { id: 'N-001', type: 'risk', title: 'Supplier risk increased', description: 'Global Materials Ltd. risk score rose to 82/100', time: '2h ago', read: false },
  { id: 'N-002', type: 'quotation', title: 'New quotation received', description: 'SteelWorks India submitted quote for RFQ-2026-001', time: '4h ago', read: false },
  { id: 'N-003', type: 'price', title: 'Price increase predicted', description: 'Steel prices forecast to rise 8.3% in 30 days', time: '6h ago', read: false },
  { id: 'N-004', type: 'inventory', title: 'Inventory reaching reorder point', description: 'Steel Components at 1,200 units (critical)', time: '8h ago', read: true },
  { id: 'N-005', type: 'savings', title: 'AI identified $18K savings opportunity', description: 'Maverick spending detected in Packaging category', time: '1d ago', read: true },
  { id: 'N-006', type: 'risk', title: 'Delivery delays detected', description: 'ThermoCast Foundry delivery delays up 15%', time: '1d ago', read: true },
];

export const purchaseOrders: PurchaseOrder[] = [
  { id: 'PO-2026-045', supplier: 'TechSource Industries', product: 'Circuit Boards', quantity: 2000, amount: 124000, status: 'Delivered', date: '2026-08-14', deliveryDate: '2026-08-20' },
  { id: 'PO-2026-044', supplier: 'Nova Electronics', product: 'Microcontrollers', quantity: 1500, amount: 67500, status: 'Shipped', date: '2026-08-13', deliveryDate: '2026-08-22' },
  { id: 'PO-2026-043', supplier: 'Apex Manufacturing', product: 'Machined Brackets', quantity: 3000, amount: 108600, status: 'Approved', date: '2026-08-11', deliveryDate: '2026-08-25' },
  { id: 'PO-2026-042', supplier: 'SteelWorks India', product: 'Steel Beams', quantity: 500, amount: 45800, status: 'Delivered', date: '2026-08-09', deliveryDate: '2026-08-15' },
  { id: 'PO-2026-041', supplier: 'AutoFast Systems', product: 'High-Tensile Bolts', quantity: 10000, amount: 48000, status: 'Approved', date: '2026-08-08', deliveryDate: '2026-08-20' },
  { id: 'PO-2026-040', supplier: 'CircuitPro Electronics', product: 'PCBs', quantity: 1000, amount: 48200, status: 'Shipped', date: '2026-08-07', deliveryDate: '2026-08-16' },
  { id: 'PO-2026-039', supplier: 'GreenPack Packaging', product: 'Corrugated Boxes', quantity: 10000, amount: 32000, status: 'Delivered', date: '2026-08-05', deliveryDate: '2026-08-12' },
  { id: 'PO-2026-038', supplier: 'PolyChem Industries', product: 'Industrial Resins', quantity: 2000, amount: 24800, status: 'Delivered', date: '2026-08-03', deliveryDate: '2026-08-10' },
  { id: 'PO-2026-037', supplier: 'Prime Components', product: 'Precision Gears', quantity: 1500, amount: 28400, status: 'Pending', date: '2026-08-15', deliveryDate: '2026-08-28' },
  { id: 'PO-2026-036', supplier: 'PlastiForm Molding', product: 'Injection Molded Parts', quantity: 5000, amount: 40000, status: 'Approved', date: '2026-08-14', deliveryDate: '2026-08-24' },
  { id: 'PO-2026-035', supplier: 'ElectroDrive Motors', product: 'Servo Motors', quantity: 200, amount: 42800, status: 'Pending', date: '2026-08-15', deliveryDate: '2026-08-29' },
  { id: 'PO-2026-034', supplier: 'WireTech Cables', product: 'Power Cables', quantity: 1000, amount: 22300, status: 'Delivered', date: '2026-08-01', deliveryDate: '2026-08-08' },
];

export const categories = [
  'Raw Materials',
  'Electronics',
  'Components',
  'Machined Parts',
  'Forged Parts',
  'Castings',
  'Chemicals',
  'Fasteners',
  'Packaging',
  'Plastics',
  'Fabrication',
  'Rubber Parts',
];

export const locations = [
  'Mumbai, India',
  'Pune, India',
  'Bengaluru, India',
  'Chennai, India',
  'Kolkata, India',
  'Hyderabad, India',
  'Coimbatore, India',
  'Vadodara, India',
  'Gurugram, India',
  'Nashik, India',
  'Rajkot, India',
  'Ahmedabad, India',
  'Faridabad, India',
  'Vapi, India',
  'Ludhiana, India',
  'Noida, India',
  'Kochi, India',
  'Jamshedpur, India',
  'Indore, India',
  'Nagpur, India',
];

export function getSupplierById(id: string): Supplier | undefined {
  return suppliers.find((s) => s.id === id);
}

export function getRFQById(id: string): RFQ | undefined {
  return rfqs.find((r) => r.id === id);
}

export function getQuotationsByRFQ(rfqId: string): Quotation[] {
  return quotations.filter((q) => q.rfqId === rfqId);
}

export { riskLevelFromScore };
